### PR TITLE
feat: add `diff-mocha.conf` to support kitty diff

### PR DESCRIPTION
**Pull request by haunt98**
Add diff mocha conf to support kitty diff

See:
- https://sw.kovidgoyal.net/kitty/kittens/diff/
- https://github.com/dracula/kitty/blob/master/diff.conf

### CODE REVIEW

**Comment by nekowinston** [comment]
This isn't really readable on my end…
CleanShot 2022-09-08 at 06 03 15

I've played around with different colours, such as a 70% `base` 30% `red`/`green` mix, which is more readable.
Would you be willing to update this PR?

**Comment by haunt98** [comment]
Please let me know which color need to update, I only copy the diff from dracula and edit some color from it.

**Comment by nekowinston** [comment]
I have changed some background colours for better readability, I'd happily merge this one if that's alright with you.

Regarding the changes in the author comment: I'll change the other ones to "Catppuccin Org" as well, once it's merged.
CleanShot 2022-09-08 at 21 43 57

**Comment by nekowinston** [comment]
Oh yeah, and please do feel free to add yourself to the “Thanks to” section on the README, or let me know how you'd like to be credited.

**Comment by haunt98** [comment]
Thanks for updating, you can merge if you want. It looks good on my machine!

**Pull request merged**
